/* ============ SOCIAL & ADS ============ */
function initializeSocial(){
  const DISP = "'PP Neue Montreal',system-ui,sans-serif";
  const BODY = "'Inter',system-ui,sans-serif";
  const MONO = "'IBM Plex Mono',ui-monospace,monospace";
  const GRAD = "linear-gradient(135deg,#4a0b2d 0%,#7d1b4e 30%,#c21052 64%,#ef4cb2 100%)";
  const INK = "#21151b";
  const L = "/brand/";

  const lbl = (t) => `<div style="font-family:${MONO};font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:#9b8a93">${t}</div>`;
  const col = (t, box) => `<div style="display:flex;flex-direction:column;gap:8px">${lbl(t)}${box}</div>`;
  const cr = (n, w, h, html, scale) => `<div style="position:relative;margin-bottom:8px"><div style="font-family:${MONO};font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#9b8a93;margin-bottom:8px">${n}</div><div style="width:${Math.min(w, 346)}px;height:auto;border-radius:6px;overflow:hidden;box-shadow:0 8px 20px rgba(0,0,0,.1);transform:scale(${scale || 1});transform-origin:top left"><div style="width:${w}px;height:${h}px;background:#fff;border-radius:6px;overflow:hidden;display:flex;align-items:center;justify-content:center">${html}</div></div></div>`;

  // Social creatives
  const socialCreatives = [
    cr("Instagram · 1080 × 1080", 1080, 1080, `<div style="width:1080px;height:1080px;background:${GRAD};color:#fff;padding:100px 88px;display:flex;flex-direction:column;justify-content:space-between;position:relative"><div style="font-family:${MONO};font-size:26px;text-transform:uppercase;letter-spacing:.14em;color:rgba(255,255,255,.9)">Procurement</div><div><div style="font-family:${DISP};font-weight:700;font-size:104px;line-height:1.02;letter-spacing:-.03em">Spend smarter</div><p style="font-family:${BODY};font-size:34px;line-height:1.45;color:rgba(255,255,255,.92);max-width:760px;margin:22px 0 0">AI-powered visibility into every dollar spent across your organization.</p></div><img src="${L}spendflo-full-colour-white.svg" alt="" style="position:absolute;left:100px;bottom:80px;height:48px;width:auto"></div>`, 0.32),

    cr("Instagram · 1080 × 1920", 1080, 1920, `<div style="width:1080px;height:1920px;background:#fff;color:${INK};padding:110px 88px;display:flex;flex-direction:column;justify-content:center;gap:36px;position:relative;border-radius:6px;overflow:hidden"><div style="position:absolute;top:0;left:0;right:0;height:16px;background:${GRAD}"></div><div style="text-align:center;margin-bottom:18px"><h2 style="font-family:${DISP};font-weight:700;font-size:86px;line-height:1.04;letter-spacing:-.03em;margin:0">Control your spend</h2></div><div style="background:#fbf8fa;border:1px solid #e9e3e6;border-radius:22px;padding:44px"><blockquote style="font-family:${DISP};font-weight:700;font-size:38px;line-height:1.32;margin:0">Real-time visibility into spend across all vendors and departments.</blockquote></div><div style="text-align:center"><img src="${L}spendflo-icon-colour.svg" alt="" style="height:64px;width:auto"></div></div>`, 0.28),

    cr("Quote card · 1080 × 1080", 1080, 1080, `<div style="width:1080px;height:1080px;background:#fff;color:${INK};padding:100px;position:relative;display:flex;flex-direction:column;justify-content:center;border-radius:6px;overflow:hidden"><div style="position:absolute;top:0;left:0;right:0;height:16px;background:${GRAD}"></div><div style="font-family:${MONO};font-size:26px;text-transform:uppercase;letter-spacing:.14em;color:#e92589;margin-bottom:28px">Better procurement</div><div style="font-family:${DISP};font-weight:700;font-size:340px;line-height:.85;letter-spacing:-.04em;color:#e92589">92%</div><p style="font-family:${DISP};font-weight:700;font-size:52px;line-height:1.25;letter-spacing:-.02em;max-width:760px;margin:28px 0 0">faster approvals with AI-powered recommendations</p><img src="${L}spendflo-full-colour-black.svg" alt="" style="position:absolute;left:100px;bottom:80px;height:48px;width:auto"></div>`, 0.32),

    cr("Testimonial · 1080 × 1080", 1080, 1080, `<div style="width:1080px;height:1080px;background:${GRAD};color:#fff;padding:100px;position:relative;display:flex;flex-direction:column;justify-content:space-between;border-radius:6px;overflow:hidden"><div style="font-family:${MONO};font-size:24px;text-transform:uppercase;letter-spacing:.14em;color:rgba(255,255,255,.8)">Customer story</div><blockquote style="font-family:${DISP};font-weight:700;font-size:92px;line-height:1.08;letter-spacing:-.03em;margin:0;text-wrap:balance">Spendflo gave us full visibility into our spending for the first time.</blockquote><div><div style="height:3px;width:130px;background:rgba(255,255,255,.55);margin-bottom:30px"></div><div style="display:flex;align-items:flex-end;justify-content:space-between"><div><div style="font-family:${DISP};font-weight:700;font-size:38px">Sarah Chen</div><div style="font-size:27px;color:rgba(255,255,255,.85);margin-top:4px">VP of Finance</div></div><img src="${L}spendflo-full-colour-white.svg" alt="" style="height:40px;width:auto"></div></div></div>`, 0.32)
  ].join("");

  // Display ads
  const leaderboard = col("Leaderboard · 728 × 90", `<div style="width:728px;height:90px;box-sizing:border-box;background:${GRAD};color:#fff;border-radius:4px;display:flex;align-items:center;gap:22px;padding:0 26px;overflow:hidden"><img src="${L}spendflo-icon-white.svg" alt="" style="height:40px;width:auto"><div style="font-family:${DISP};font-weight:700;font-size:26px;letter-spacing:-.02em;line-height:1.05;flex:1">Spend with visibility</div><span style="background:${INK};color:#fff;font-family:${DISP};font-weight:700;font-size:15px;padding:11px 22px;border-radius:8px;white-space:nowrap">Learn more</span></div>`);

  const billboard = col("Billboard · 970 × 250", `<div style="width:970px;height:250px;box-sizing:border-box;background:${GRAD};color:#fff;border-radius:6px;padding:40px 48px;position:relative;display:flex;flex-direction:column;justify-content:center;overflow:hidden"><div style="font-family:${MONO};font-size:14px;text-transform:uppercase;letter-spacing:.14em;color:rgba(255,255,255,.85);margin-bottom:14px">AI procurement platform</div><div style="font-family:${DISP};font-weight:700;font-size:50px;line-height:1.02;letter-spacing:-.03em;max-width:640px">Spend smarter, faster</div><span style="align-self:flex-start;margin-top:22px;background:${INK};color:#fff;font-family:${DISP};font-weight:700;font-size:17px;padding:13px 26px;border-radius:8px">Learn more →</span><img src="${L}spendflo-full-colour-white.svg" alt="" style="position:absolute;top:36px;right:48px;height:30px;width:auto"></div>`);

  const medrect = col("Medium rectangle · 300 × 250", `<div style="width:300px;height:250px;box-sizing:border-box;background:#fff;color:${INK};border-radius:6px;padding:26px;position:relative;display:flex;flex-direction:column;justify-content:center;overflow:hidden;border:1px solid #e9e3e6"><div style="position:absolute;top:0;left:0;right:0;height:8px;background:${GRAD}"></div><div style="font-family:${MONO};font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#e92589;margin-bottom:10px">Procurement · AI</div><div style="font-family:${DISP};font-weight:700;font-size:30px;line-height:1.05;letter-spacing:-.02em">Control your spend</div><span style="align-self:flex-start;margin-top:18px;background:#e92589;color:#fff;font-family:${DISP};font-weight:700;font-size:14px;padding:10px 20px;border-radius:8px">Learn more</span><img src="${L}spendflo-full-colour-black.svg" alt="" style="position:absolute;left:26px;bottom:22px;height:18px;width:auto"></div>`);

  const lgrect = col("Large rectangle · 336 × 280", `<div style="width:336px;height:280px;box-sizing:border-box;background:${GRAD};color:#fff;border-radius:6px;padding:28px;position:relative;display:flex;flex-direction:column;justify-content:center;overflow:hidden"><div style="font-family:${DISP};font-weight:700;font-size:96px;letter-spacing:-.04em;line-height:.9">40%</div><div style="font-family:${DISP};font-weight:700;font-size:22px;line-height:1.2;margin-top:10px;max-width:240px">savings in procurement costs</div><img src="${L}spendflo-full-colour-white.svg" alt="" style="position:absolute;left:28px;bottom:24px;height:22px;width:auto"></div>`);

  const halfpage = col("Half page · 300 × 600", `<div style="width:300px;height:600px;box-sizing:border-box;background:#fff;color:${INK};border-radius:6px;padding:32px 28px;position:relative;display:flex;flex-direction:column;justify-content:center;overflow:hidden;border:1px solid #e9e3e6"><div style="position:absolute;top:0;left:0;right:0;height:10px;background:${GRAD}"></div><div style="font-family:${MONO};font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#e92589;margin-bottom:14px">AI-powered insights</div><div style="font-family:${DISP};font-weight:700;font-size:40px;line-height:1.03;letter-spacing:-.03em">Visibility into every spend</div><div style="display:flex;flex-direction:column;gap:10px;margin:22px 0;font-size:14px;font-family:${BODY}"><div style="display:flex;gap:10px;align-items:center"><span style="color:#e92589;font-weight:700">&check;</span> Real-time visibility</div><div style="display:flex;gap:10px;align-items:center"><span style="color:#e92589;font-weight:700">&check;</span> Intelligent sourcing</div><div style="display:flex;gap:10px;align-items:center"><span style="color:#e92589;font-weight:700">&check;</span> Automated approvals</div></div><span style="align-self:flex-start;background:#e92589;color:#fff;font-family:${DISP};font-weight:700;font-size:15px;padding:12px 24px;border-radius:8px">Learn more</span><img src="${L}spendflo-full-colour-black.svg" alt="" style="position:absolute;left:28px;bottom:26px;height:18px;width:auto"></div>`);

  const skyscraper = col("Skyscraper · 160 × 600", `<div style="width:160px;height:600px;box-sizing:border-box;background:linear-gradient(180deg,#d9085f,#e92589);color:#fff;border-radius:6px;padding:26px 20px;position:relative;display:flex;flex-direction:column;justify-content:center;overflow:hidden"><div style="font-family:${DISP};font-weight:700;font-size:38px;line-height:1.02;letter-spacing:-.03em">Smarter spend</div><span style="align-self:flex-start;margin-top:18px;background:${INK};color:#fff;font-family:${DISP};font-weight:700;font-size:13px;padding:10px 16px;border-radius:8px">Learn →</span><img src="${L}spendflo-full-colour-white.svg" alt="" style="position:absolute;left:20px;bottom:24px;height:18px;width:auto"></div>`);

  const mobile = col("Mobile · 320 × 100", `<div style="width:320px;height:100px;box-sizing:border-box;background:${GRAD};color:#fff;border-radius:4px;display:flex;align-items:center;gap:14px;padding:0 18px;overflow:hidden"><img src="${L}spendflo-icon-white.svg" alt="" style="height:34px;width:auto"><div style="font-family:${DISP};font-weight:700;font-size:18px;line-height:1.1;letter-spacing:-.02em;flex:1">Smart procurement</div><span style="background:${INK};color:#fff;font-family:${DISP};font-weight:700;font-size:12px;padding:8px 14px;border-radius:6px;white-space:nowrap">Learn</span></div>`);

  const displayAds = [leaderboard, billboard, medrect, lgrect, mobile, halfpage, skyscraper].join("");

  // Populate
  const socialDiv = document.getElementById("socialCreatives");
  const displayDiv = document.getElementById("displayAds");
  
  if (socialDiv) {
    socialDiv.querySelector("div").innerHTML = socialCreatives;
  }
  if (displayDiv) {
    displayDiv.querySelector("div").innerHTML = displayAds;
  }
}
